name: Secret and environment variables

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log Level"
        required: true
        default: "info"
        type: choice
        options:
          - debug
          - info
          - warn
          - error
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: string

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Inputs
        run: |
          echo "manual trigger runs successfully"
          echo "Log Level: $ {{ github.event.inputs.logLevel }} " 
          echo "Environment: $ {{ github.event.inputs.environment }}"
